INSERT INTO tb_crop (
    id, crop_id, crop_kor_name, crop_eng_name,
    category, crops_image, crop_cost, ugly_cost,
    crop_description, deleted, created_at, updated_at
)
VALUES
    ('1', '151', '고구마', 'Sweet Potato', '식량작물',
     'sweet_potato.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('2', '152', '감자', 'Potato', '식량작물',
     'potato.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('3', '212', '양배추', 'Cabbage', '채소',
     'cabbage.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('4', '211', '배추', 'Chinese Cabbage', '채소',
     'chinese_cabbage.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('5', '221', '수박', 'Watermelon', '채소',
     'watermelon.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('6', '225', '토마토', 'Tomato', '채소',
     'tomato.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('7', '422', '방울토마토', 'Cherry Tomato', '채소',
     'cherry_tomato.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('8', '257', '멜론', 'Melon', '채소',
     'melon.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('9', '213', '시금치', 'Spinach', '채소',
     'spinach.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('10', '224', '호박', 'Pumpkin', '채소',
     'pumpkin.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('11', '231', '무', 'Radish', '채소',
     'radish.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('12', '214', '상추', 'Lettuce', '채소',
     'lettuce.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('13', '226', '딸기', 'Strawberry', '채소',
     'strawberry.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('14', '222', '참외', 'Oriental Melon', '채소',
     'oriental_melon.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('15', '246', '파', 'Green Onion', '채소',
     'green_onion.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('16', '245', '양파', 'Onion', '채소',
     'onion.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('17', '411', '사과', 'Apple', '과일',
     'apple.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('18', '412', '배', 'Pear', '과일',
     'pear.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('19', '413', '복숭아', 'Peach', '과일',
     'peach.jpg', NULL, NULL, NULL, 'N', NOW(), NOW()),
    ('20', '415', '감귤', 'Tangerine', '과일',
     'tangerine.jpg', NULL, NULL, NULL, 'N', NOW(), NOW());
